version: '3.5'                          

services:                               

  mysql:                                 
    image: mariadb:10.5                  
    container_name: zbx-mysql            
    environment:                         
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: zabbix             
      MYSQL_USER: zabbix                 
      MYSQL_PASSWORD: zabbix_pass      
    volumes:
      - zabbix-db:/var/lib/mysql         
    restart: unless-stopped              

  zabbix-server:                         
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest    
    container_name: zbx-server          
    environment:
      DB_SERVER_HOST: mysql              
      MYSQL_DATABASE: zabbix            
      MYSQL_USER: zabbix                 
      MYSQL_PASSWORD: zabbix_pass        
    depends_on:
      - mysql                           
    ports:
      - "10051:10051"                    
    restart: unless-stopped              

  zabbix-web:                            
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest 
    container_name: zbx-web              
    environment:
      DB_SERVER_HOST: mysql              
      MYSQL_DATABASE: zabbix             
      MYSQL_USER: zabbix                 
      MYSQL_PASSWORD: zabbix_pass       
      ZBX_SERVER_HOST: zabbix-server    
      PHP_TZ: Asia/Ho_Chi_Minh           
    ports:
      - "8080:8080"                     
    depends_on:
      - zabbix-server                   
    restart: unless-stopped          

volumes:
  zabbix-db:                             